services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-net
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "ipa2025"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net
    env_file:
      - .env
  
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"
  #   networks:
  #     - app-net
  #   env_file:
  #     - .env
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
  #     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
  #   volumes:
  #     - rabbitmq-data:/var/lib/rabbitmq

  scheduler:
    build: ./scheduler
    networks:
      - app-net
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASSWORD}
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "ipa2025"

volumes:
  mongo-data:
  # rabbitmq-data:

networks:
  app-net: